module Main where

main :: IO ()
main = do
  putStrLn "One done!"
  putStrLn "Two done!"
  putStrLn "Three done!"
  putStrLn "Four done!"
  putStrLn "Five done!"
  putStrLn "Six done!"
  putStrLn "Seven done!"
  putStrLn "Eight done!"
  putStrLn "Nine done!"
  putStrLn "Ten done!"
  putStrLn "Eleven done!"
  putStrLn "Twelve done!"
  putStrLn "Thirteen done!"
  putStrLn "Fourteen done!"
  -- putStrLn "Fifteen done!"
  -- putStrLn "Sixteen done!"
  putStrLn "Seventeen done!"
  putStrLn "Eighteen done!"
  -- putStrLn "Nineteen done!"
  -- putStrLn "Twenty done!"
  -- putStrLn "Twenty-One done!"
  -- putStrLn "Twenty-Two done!"
  -- putStrLn "Twenty-Three done!"
  -- putStrLn "Twenty-Four done!"
  -- putStrLn "Twenty-Five done!"
